import "./globals.css";
import Providers from "./utils/Providers";
import { Barlow } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import NavBar from "./_components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} antialiased h-screen bg-slate-100`}>
        <Providers>
          <NavBar />
          <main className="pt-40 pb-20bg-slate-100">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
