import "./globals.css";
import Providers from "./utils/Providers";
import { Provider } from "@/components/ui/provider";
import { Barlow } from "next/font/google";
import NavBar from "./components/navbar";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} antialiased h-screen bg-slate-100`}>
        <Provider>
          <Providers>
            <NavBar />
            <Toaster position="bottom-center" reverseOrder={false} />
            <main className="pt-10 pb-20 bg-slate-100">{children}</main>
          </Providers>
        </Provider>
      </body>
    </html>
  );
}
