import "./globals.css";
import Providers from "./utils/Providers";
import { Barlow } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
